// npx playwright test  ---> it runs all the test files you have in tests file

// npx playwright test --headed   ---> it runs the test in visable/frontend 

// npx playwright test --headless   ----> it runs the test in bacend/hides the execution it gives you result 

// npx playwright test test/scripttitle.spec.js   ---> it runs a specifc script inside a file 

// npx playwright test -g "block name"   ---> it is used to execute base on the test block name which is containg that name 

// npx playwright test test/scripttitle.spec.js  --debug  ---> it is used to exicute your scrip parallely with automation line by line 

// npx playwright test --last-failed   ---> it is used to exicute last failed scripts 

// npx playwright test --project browser name    ---> it is used to test script in a specific browser

// npx playwright show-report   ---> Opens the HTML test report generated by Playwright after a test run

// npx playwright test --grep @tagname --> it is used for exicuting only tests with that tag   // to use this you need to add @tagname to your test name for one test we can add multiple tags

import{test, expect} from '@playwright/test';

test('locators demo', async({page})=>{

    // navigate to url
    await page.goto('https://www.amazon.in/');

    // locator using id
    await page.locator('#twotabsearchtextbox').fill('css #id'); // # is used for id and . is for class

    // locator using class
    // . is used for class in css and [class=''] is used for class in xpath
    await page.locator("[class='nav-search-scope nav-sprite']").click(); 

    // locator using text
    await page.locator('#searchDropdownBox').selectOption('Electronics')
    
});

